version: '3.1'

services:
  
  userservice:
    container_name: user_service
    build:
      context: SocialNetwork/.
      dockerfile: Dockerfile
    ports:
      - "8189:8189"
    depends_on:
      - postgres_user_service
      - postservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_user_service:5432/user_service_db
      SERVER_PORT: 8189
      SPRING_DATASOURCE_USER: kattsyn
      SPRING_DATASOURCE_PASSWORD: katt
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      JWT_SECRET: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
      JWT_LIFETIME: 30m
      API_PATH: api/v1
      GRPC_CLIENT_POST-SERVICE_ADDRESS: postservice:9090
  
  postgres_user_service:
    image: postgres:latest
    container_name: user_service_db
    environment:
      POSTGRES_USER: kattsyn
      POSTGRES_PASSWORD: katt
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
     
  postservice:
    container_name: post_service
    build:
      context: PostService/.
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgres_post_service
    environment:
      GRPC_SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_post_service:5433/post_service_db
      SPRING_DATASOURCE_USER: kattsyn
      SPRING_DATASOURCE_PASSWORD: katt
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
  
  postgres_post_service:
    image: postgres:latest
    container_name: post_service_db
    environment:
      POSTGRES_USER: kattsyn
      POSTGRES_PASSWORD: katt
      POSTGRES_DB: post_service_db
      PGPORT: 5433
    ports:
      - "5433:5433"
  
  statservice:
    container_name: stat_service
    build:
      context: StatService/.
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    depends_on:
      - postgres_stat_service
      - postservice
    environment:
      GRPC_SERVER_PORT: 9091
      GRPC_CLIENT_POST-SERVICE_ADDRESS: postservice:9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_stat_service:5434/stat_service_db
      SPRING_DATASOURCE_USER: kattsyn
      SPRING_DATASOURCE_PASSWORD: katt
      SPRING_JPA_HIBERNATE_DDL-AUTO: create

  postgres_stat_service:
    image: postgres:latest
    container_name: stat_service_db
    environment:
      POSTGRES_USER: kattsyn
      POSTGRES_PASSWORD: katt
      POSTGRES_DB: stat_service_db
      PGPORT: 5434
    ports:
      - "5434:5434"