spring:
  application:
    name: StatService
  datasource:
    url: jdbc:postgresql://localhost:5432/stat_service_db
    username: kattsyn
    password: katt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
grpc:
  server:
    port: 9091
