spring:
  application:
    name: PostService
  datasource:
    url: jdbc:postgresql://localhost:5432/post_service_db
    username: kattsyn
    password: katt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8190
