spring:
  application:
    name: PostService
  datasource:
    url: jdbc:postgresql://localhost:5433/post_service_db
    username: kattsyn
    password: katt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: "broker:9099"
      client-id: "post-service"
grpc:
  server:
    port: 9090