server:
  port: 8189
  error:
    include-message: always
spring:
  application:
    name: SocialNetwork
  datasource:
    url: jdbc:postgresql://postgres_user_service:5432/user_service_db
    username: kattsyn
    password: katt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      client-id: "user-service"
      bootstrap-servers: "broker:9099"
      properties:
        spring:
          json:
            trusted:
              packages: "kattsyn.dev.SocialNetwork.dtos.statservice, java.util, java.lang"
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
api:
  path: api/v1
grpc:
  client:
    post-service:
      address: static://localhost:9090
      negotiation-type: plaintext