server:
  port: 8189
  error:
    include-message: always
spring:
  application:
    name: SocialNetwork
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: kattsyn
    password: katt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
api:
  path: api/v1
grpc:
  #server:
    #address: localhost:9090
  client:
    post-service:
      address: static://localhost:9090
      negotiation-type: plaintext