version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: post_service
    environment:
      POSTGRES_USER: kattsyn
      POSTGRES_PASSWORD: katt
      POSTGRES_DB: post_service_db
    ports:
      - "5432:5432"